apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - especialista-java.yaml

images:
  - name: especialista-java
    newName: sidartasilva/algaworks-especialista-java-mvn
    newTag: 2fbabcce3377649e5c8ef9c3af04ed996193baad
